(Start of program)

(GCode generated by Gemini Aero Foam v1.0.0.6)
(Date : 2025-06-12 13:49:56)

(Project : Z:/zephyrwhyte/fuse_new/moto20mmproj.txt)
(Profiles : motoframe20mm.dxf, motoframe20mm.dxf)
(Chords : 150.0 mm, 150.0 mm)
(Length : 154.0 mm, sweep : 0.0 mm)
(Wing : left)

(Machine : My CNC)
(Hot wire: NiCr, 800 mm x 0.3 mm, 24 V)

(Foam : Yellow foam 40 kg/m3)
(Cutting speed = 4.9 mm/s)
(Cutting heat = 80.0 %)
(Cutting duration = 0 min 1 s)

(Set working origin to current position)
G92 X0.0000 Y0.0000 A0.0000 Z0.0000 
(Set coordinates to absolute and in mm)
G90 G21
(Use inverse time feedrate, so F is in min-1)
G93

(Set heating power : 0-100% scaled to S range = 0-1000)
S800

(Go to entry of block and halt 1 mm before)
G00 X0.0000 Y10.5500 A0.0000 Z10.5500 
G00 X9.0000 Y10.5500 A9.0000 Z10.5500 

(Wait user to press the resume key)
M0
(Start heating)
M3
(Pre-heating delay)
G04 P4.0

(Cut the foam)
G01 X10.0000 Y10.5500 A10.0000 Z10.5500 F294.0000 
G01 X13.0000 Y10.5500 A13.0000 Z10.5500 F98.0000 
G01 X162.4500 Y10.5500 A162.4500 Z10.5500 F1.9672 
G01 X162.4500 Y29.4500 A162.4500 Z29.4500 F15.5556 
G01 X12.4500 Y29.4500 A12.4500 Z29.4500 F1.9600 
G01 X11.9000 Y28.9000 A11.9000 Z28.9000 F377.9807 
G01 X11.9000 Y29.4500 A11.9000 Z29.4500 F534.5455 
G01 X10.0000 Y29.4500 A10.0000 Z29.4500 F154.7368 
G01 X9.0000 Y29.4500 A9.0000 Z29.4500 F294.0000 

(Post-heating delay)
G04 P4.0
(Stop heating)
M5

(Return to machine origin)
G00 X0.0000 Y29.4500 A0.0000 Z29.4500 
G00 X0.0000 Y0.0000 A0.0000 Z0.0000 

(Go back to normal feedrate)
G94
(Restore previous working origin)
G92.1
(Stop motors)
M2

(End of program)