(Start of program)

(GCode generated by Gemini Aero Foam v1.0.0.7)
(Date : 2025-09-24 17:42:29)

(Project : C:/Shared/_zephyr_v5/Fuselage/proj/10mmdetail.txt)
(Profiles : 10mmdetail.dxf, 10mmdetail.dxf)
(Chords : 64.7 mm, 64.7 mm)
(Length : 10.0 mm, sweep : 0.0 mm)
(Wing : left)

(Machine : My CNC)
(Hot wire: NiCr, 800 mm x 0.3 mm, 24 V)

(Foam : Yellow foam 40 kg/m3)
(Cutting speed = 3.5 mm/s)
(Cutting heat = 80.0 %)
(Cutting duration = 0 min 1 s)

(Set working origin to current position)
G92 X0.0000 Y0.0000 A0.0000 Z0.0000 
(Set coordinates to absolute and in mm)
G90 G21
(Use inverse time feedrate, so F is in min-1)
G93

(Set heating power : 0-100% scaled to S range = 0-1000)
S800

(Go to entry of block and halt 1 mm before)
G00 X0.0000 Y14.4363 A0.0000 Z14.4363 
G00 X4.0000 Y14.4363 A4.0000 Z14.4363 

(Wait user to press the resume key)
M0
(Start heating)
M3
(Pre-heating delay)
G04 P4.0

(Cut the foam)
G01 X5.0000 Y14.4363 A5.0000 Z14.4363 F210.0000 
G01 X14.5000 Y14.4363 A14.5000 Z14.4363 F22.1053 
G01 X14.5000 Y34.0037 A14.5000 Z34.0037 F10.7322 
G01 X80.2000 Y50.3429 A80.2000 Z50.3429 F3.1019 
G01 X80.2000 Y9.5000 A80.2000 Z9.5000 F5.1416 
G01 X46.8512 Y9.5000 A46.8512 Z9.5000 F6.2971 
G01 X46.8560 Y13.4363 A46.8560 Z13.4363 F53.3489 
G01 X14.5000 Y13.4363 A14.5000 Z13.4363 F6.4903 
G01 X14.0000 Y12.9363 A14.0000 Z12.9363 F296.9848 
G01 X14.0000 Y13.4363 A14.0000 Z13.4363 F420.0000 
G01 X5.0000 Y13.4363 A5.0000 Z13.4363 F23.3333 
G01 X4.0000 Y13.4363 A4.0000 Z13.4363 F210.0000 

(Post-heating delay)
G04 P4.0
(Stop heating)
M5

(Return to machine origin)
G00 X0.0000 Y13.4363 A0.0000 Z13.4363 
G00 X0.0000 Y0.0000 A0.0000 Z0.0000 

(Go back to normal feedrate)
G94
(Restore previous working origin)
G92.1
(Stop motors)
M2

(End of program)