(Start of program)

(GCode generated by Gemini Aero Foam v1.0.0.6)
(Date : 2025-06-12 13:52:58)

(Project : Z:/zephyrwhyte/fuse_new/fuse40proj.txt)
(Profiles : fusecenter40mm.dxf, fusecenter40mm.dxf)
(Chords : 100.0 mm, 100.0 mm)
(Length : 154.0 mm, sweep : 0.0 mm)
(Wing : left)

(Machine : My CNC)
(Hot wire: NiCr, 800 mm x 0.3 mm, 24 V)

(Foam : Yellow foam 40 kg/m3)
(Cutting speed = 4.9 mm/s)
(Cutting heat = 80.0 %)
(Cutting duration = 0 min 2 s)

(Set working origin to current position)
G92 X0.0000 Y0.0000 A0.0000 Z0.0000 
(Set coordinates to absolute and in mm)
G90 G21
(Use inverse time feedrate, so F is in min-1)
G93

(Set heating power : 0-100% scaled to S range = 0-1000)
S800

(Go to entry of block and halt 1 mm before)
G00 X0.0000 Y43.5500 A0.0000 Z43.5500 
G00 X4.0000 Y43.5500 A4.0000 Z43.5500 

(Wait user to press the resume key)
M0
(Start heating)
M3
(Pre-heating delay)
G04 P4.0

(Cut the foam)
G01 X5.0000 Y43.5500 A5.0000 Z43.5500 F294.0000 
G01 X8.0000 Y43.5500 A8.0000 Z43.5500 F98.0000 
G01 X108.5500 Y43.5500 A108.5500 Z43.5500 F2.9239 
G01 X108.5500 Y2.4500 A108.5500 Z2.4500 F7.1533 
G01 X7.4500 Y2.4500 A7.4500 Z2.4500 F2.9080 
G01 X6.9000 Y1.9000 A6.9000 Z1.9000 F377.9807 
G01 X6.9000 Y2.4500 A6.9000 Z2.4500 F534.5455 
G01 X5.0000 Y2.4500 A5.0000 Z2.4500 F154.7368 
G01 X4.0000 Y2.4500 A4.0000 Z2.4500 F294.0000 

(Post-heating delay)
G04 P4.0
(Stop heating)
M5

(Return to machine origin)
G00 X0.0000 Y2.4500 A0.0000 Z2.4500 
G00 X0.0000 Y0.0000 A0.0000 Z0.0000 

(Go back to normal feedrate)
G94
(Restore previous working origin)
G92.1
(Stop motors)
M2

(End of program)