(Start of program)

(GCode generated by Gemini Aero Foam v1.0.1.6d)
(Date : 2026-03-04 12:26:08)

(Project : fus_12mm_x2)
(Wing right only)
(Profiles : fus_18mm_x2.dxf, fus_18mm_x2.dxf)
(Chords : 100.1 mm, 100.1 mm)
(Length : 100.0 mm, sweep : 0.0 mm)
(Block chords : 115.1 mm, 115.1 mm)
(Block thickness : 50.0 mm)
(Block lateral distance from left side of table : 300.0 mm)
(Block longitudinal distance of root trailing edge from working origin : 25.0 mm)
(Block vertical distance from working origin : 0.0 mm)

(Machine : My CNC)
(Machine axis max travels : horizontal 660.0 mm, vertical 360.0 mm)
(Machine axis distance left to right axis : 855.0 mm)
(Table distance from axis : left 0.0 mm, right 0.0 mm)

(Hot wire : NiCr, 800 mm x 0.3 mm, 24 V)
(Heating range : OFF S=0, ON full power S=1000)
(Max heating allowed : 100.0%)

(Foam : Yellow foam 40 kg/m3)
(Cutting speed = 3.5 mm/s)
(Cutting heat = 80%, S=800)
(Cutting duration = 1 min 36 s)

(Set coordinates to absolute and in mm)
G90 G21
(Use inverse time feedrate, so F is in min-1)
G93

(Go to wire cleaning position)
G00 X0.0000 Y50.0000 A0.0000 Z50.0000 
(Set the wire to full allowed power)
M3 S1000
(Wait user to press the resume key)
M0
(Stop heating)
M5
(Wait 3s)
G04 P3.0
(Return to working origin)
G00 X0.0000 Y0.0000 A0.0000 Z0.0000 

(Go to block entry and halt 1 mm before)
G00 X0.0000 Y5.5000 A0.0000 Z5.5000 
G00 X24.0000 Y5.5000 A24.0000 Z5.5000 

(Wait user to press the resume key)
M0
(Set the wire to cutting power)
M3 S800
(Pre-heating delay)
G04 P4.0

(Cut the foam)
G01 X25.0000 Y5.5000 A25.0000 Z5.5000 F210.0000 
G01 X34.5000 Y5.5000 A34.5000 Z5.5000 F22.1053 
G01 X34.5000 Y36.6536 A34.5000 Z36.6536 F6.7408 
G01 X135.6000 Y27.8294 A135.6000 Z27.8294 F2.0693 
G01 X135.6000 Y4.5000 A135.6000 Z4.5000 F9.0015 
G01 X34.5000 Y4.5000 A34.5000 Z4.5000 F2.0772 
G01 X34.0000 Y4.0000 A34.0000 Z4.0000 F296.9848 
G01 X34.0000 Y4.5000 A34.0000 Z4.5000 F420.0000 
G01 X25.0000 Y4.5000 A25.0000 Z4.5000 F23.3333 
G01 X24.0000 Y4.5000 A24.0000 Z4.5000 F210.0000 

(Post-heating delay)
G04 P4.0
(Stop heating)
M5

(Return to machine origin)
G00 X0.0000 Y4.5000 A0.0000 Z4.5000 
G00 X0.0000 Y0.0000 A0.0000 Z0.0000 

(Go back to normal feedrate)
G94
(Stop motors)
M2

(End of program)