(Start of program)

(GCode generated by Gemini Aero Foam v1.0.0.7)
(Date : 2025-09-24 19:07:08)

(Project : C:/Shared/_zephyr_v5/Fuselage/proj/12mmdetail.txt)
(Profiles : 12mmdetail.dxf, 12mmdetail.dxf)
(Chords : 147.7 mm, 147.7 mm)
(Length : 12.0 mm, sweep : 0.0 mm)
(Wing : left)

(Machine : My CNC)
(Hot wire: NiCr, 800 mm x 0.3 mm, 24 V)

(Foam : Yellow foam 40 kg/m3)
(Cutting speed = 3.5 mm/s)
(Cutting heat = 80.0 %)
(Cutting duration = 0 min 1 s)

(Set working origin to current position)
G92 X0.0000 Y0.0000 A0.0000 Z0.0000 
(Set coordinates to absolute and in mm)
G90 G21
(Use inverse time feedrate, so F is in min-1)
G93

(Set heating power : 0-100% scaled to S range = 0-1000)
S800

(Go to entry of block and halt 1 mm before)
G00 X0.0000 Y10.7000 A0.0000 Z10.7000 
G00 X4.0000 Y10.7000 A4.0000 Z10.7000 

(Wait user to press the resume key)
M0
(Start heating)
M3
(Pre-heating delay)
G04 P4.0

(Cut the foam)
G01 X5.0000 Y10.7000 A5.0000 Z10.7000 F210.0000 
G01 X14.3000 Y10.7000 A14.3000 Z10.7000 F22.5806 
G01 X14.3000 Y55.4390 A14.3000 Z55.4390 F4.6939 
G01 X163.4000 Y80.0406 A163.4000 Z80.0406 F1.3897 
G01 X163.4000 Y9.3000 A163.4000 Z9.3000 F2.9686 
G01 X14.3000 Y9.3000 A14.3000 Z9.3000 F1.4085 
G01 X13.6000 Y8.6000 A13.6000 Z8.6000 F212.1320 
G01 X13.6000 Y9.3000 A13.6000 Z9.3000 F300.0000 
G01 X5.0000 Y9.3000 A5.0000 Z9.3000 F24.4186 
G01 X4.0000 Y9.3000 A4.0000 Z9.3000 F210.0000 

(Post-heating delay)
G04 P4.0
(Stop heating)
M5

(Return to machine origin)
G00 X0.0000 Y9.3000 A0.0000 Z9.3000 
G00 X0.0000 Y0.0000 A0.0000 Z0.0000 

(Go back to normal feedrate)
G94
(Restore previous working origin)
G92.1
(Stop motors)
M2

(End of program)